
name: abi-app-user
alias: /user

services:
  abi-app-user:
    type: abi-app-user
    collection: user/
    db: abi-db
    secret: kewofji43490jfls
  abi-db:
    type: abi-db
    addr: 127.0.0.1:8082
    