name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: docker.io/nginx/unit:1.27.0-go1.18
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: go mod tidy
      run: go mod tidy

    - name: go build
      run: go build -v ./...


