name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: go build
      run: docker run --rm -v $(pwd):/workdir -w "/workdir" docker.io/nginx/unit:1.27.0-go1.18 /workdir/.github/ci/build.sh



